version: '2.2'
services:
  web:
    image: aspendigital/octobercms:develop-php7.4-apache
    ports:
      - 80:80
    volumes:
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./html/.env:/var/www/html/.env
      - ./html/plugins:/var/www/html/plugins
      - ./html/storage/app:/var/www/html/storage/app
      - ./html/storage/logs:/var/www/html/storage/logs
      - ./html/storage/database.sqlite:/var/www/html/storage/database.sqlite
      - ./html/themes:/var/www/html/themes
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql #DB_HOST should match the service name of the database container
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - XDEBUG_ENABLE=true

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms
    volumes:
      - ./mysqlconf:/etc/mysql/conf.d/:ro
      - dbdata:/var/lib/mysql
volumes:
    dbdata:
